# Setup
title:        Freeposte.io
tagline:      Simple yet full-featured mail server as a set of Docker images
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       kaiyou
  url:        https://kaiyou.fr

# Main links
links:
  documentaiton: https://github.com/kaiyou/freeposte.io/wiki
  setup:      https://github.com/kaiyou/freeposte.io/blob/master/INSTALL.md
  github:     https://github.com/kaiyou/freeposte.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
